steps:
  - name: gcr.io/cloud-builders/gcloud
    args: 
      [
        'functions', 'deploy', 'pubFileMetaData',
        '--source https://source.developers.google.com/projects/blaise-dev-258914/repos/github_onsdigital_blaise-gcp-publish-bucket-metadata',
        '--runtime python37',
        '--trigger-resource blaise-dev-258914-results',
        '--trigger-event google.storage.object.finalize',
        '--set-env-vars PROJECT_ID=blaise-dev-258914,TOPIC_NAME=blaise-dev-258914-export-topic',
        '--region=europe-west2'
      ]
