steps:
# Connect to the repository
- name: 'gcr.io/cloud-builders/git'
  id: Clone repository
  args: ['clone', 'https://github.com/ONSdigital/blaise-gcp-publish-bucket-metadata.git']

- name: 'gcr.io/cloud-builders/gcloud'
  id: Checkout branch
  entrypoint: /bin/sh
  args: 
  - '-c'
  - |
    cd blaise-gcp-publish-bucket-metadata
    git checkout LU-5110

# 
- name: 'gcr.io/cloud-builders/gcloud'
  id: Configure user
  args:
  - functions
  - deploy
  - pubFileMetaData 
    --source=. 
    --region=europe-west2 
    --runtime=python37 
    --trigger-bucket=blaise-dev-258914-results 
    --trigger-resource=blaise-dev-258914-results 
    --trigger-topic=blaise-dev-258914-export-topic 
    --trigger-event google.storage.object.finalize
