steps:
  - name: gcr.io/cloud-builders/gcloud@sha256:4ea77d19d7336d5a8dc4ae0e609d7f5b45fca067c34b70d7ed6740af229392c6
    id: function-deploy-meta-publish
    args: 
      ['functions', 'deploy', 'goWithTheDataFlow',
          '--source https://source.developers.google.com/projects/blaise-dev-258914/repos/github_onsdigital_blaise-gcp-publish-bucket-metadata',
          '--runtime python37',
          '--trigger-resource blaise-dev-258914-results',
          '--trigger-event google.storage.object.finalize',
          '--set-env-vars PROJECT_ID=blaise-dev-258914',
          '--set-env-vars TOPIC_NAME=blaise-dev-258914-export-topic',
          '--region=europe-west2'
      ]
    dir: 'cloud-function'
    waitFor: []