steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Configure user
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      gcloud functions deploy pubFileMetaData \
      --source https://source.developers.google.com/projects/blaise-dev-258914/repos/github_onsdigital_blaise-gcp-publish-bucket-metadata \
      --runtime=python37 \
      --trigger-topic=blaise-dev-258914-export-topic \
      --trigger-bucket=blaise-dev-258914-results \
      --trigger-event=google.storage.object.finalize \
      --blaise-dev-258914-export-topic \
      --set-env-vars=[PROJECT_ID=blaise-dev-258914,TOPIC_NAME=blaise-dev-258914-export-topic] \
      --region=europe-west2
